### ISSUE TITLE
[Bug] It is possible to select but not really set output voltage value that is not supported

### ISSUE THREAD

**Issue by cedel1** [hardkernel/smartpower3#31]
When you select output voltage value for channel, the values selectable by encoder are from 3V to 20V, in 100mV increments.

But that is not wholly supported by the STPD01 chip used. According to STPD01 documentation:

Vout has 240 (8 bit) settable values, 3 V to 5.9 V with 20 mV step, 5.9 V to 11 V with 100 mV step, 11 V to 20 V with
200 mV step.

So, for example, it is possible to select a value of 11.3V, but that is not supported.

Luckily, the library governing STPD01 checks for these steps and only allows to set valid output voltage values. Unsupported values are either set to 3V (if the value to be set is equal or lower than 3V) or 20V (if the value to be set is equal or higher than 20V).
Values that are within the permissible range of 3-20V but do not conform to the above step values are set as the nearest lower step (so it is as close as possible, but not above the selected value).

The above selected value of 11.3V is output as 11.2V, which is also shown on the meter display.

I think unsupported values should not be selectable in the UI.

**Comment by cedel1** [comment]
I am looking into the problem, hopefully there will be reasonable (not too complicated and fast) solution.

At this moment I don't think allowing only 200mV steps across the whole range is a solution (even though that would be easiest thing to do).

**Comment by tomek-szczesny** [comment]
I think this is the place that ought to be fixed:
https://github.com/hardkernel/smartpower3/blob/a02b1de586912a13717e7fd9f376045b9a40b232/smartpower3/channel.cpp#L303-L306

Obviously the best idea is to apply if/else ladder to support all three ranges. Well spotted, by the way, I've never used a weird voltage so I never caught this one. :)

To make matters simpler, I think it's safe to limit `volt_set` as either 1, 0, or -1. Then the logic will be simpler, I guess.

**Comment by cedel1** [comment]
That's only one of the places - `setVolt` (mode 0) has the same logic and also `clampVariableToRange` function needs to know if the number of "steps" is within the permissible range.

Also, I wouldn't want to limit `volt_set` to just three value - if I see it correctly it's basically the number of steps the encoder has output and I'm afraid that it would cause problems if you try to move the encoder fast (move across the voltage range, let's say from 12V to 5V as fast as possible).

I am trying a slightly different approach by modifying the number of encoder steps in place but no correct behavior so far. 
Also, ideally, I'd like it to handle non-standard (non UI settable) values set for example by future remote control.

If size, space and computing power were not at a premium (read: if the problem was in a software on a standard computer), I would try a different approach - make an array of all the permissible voltage values and move the "steps" as changing the index of the value on that array. Than minimum and maximum permissible steps could be counted as distance to the ends of the array.

I am feeling dumb these days so it does not progress as fast as I'd like.

> Well spotted, by the way

Pure luck, I figured it out while testing a task that raised the voltage gradually step by step and the output would not set (but would display as set) the odd values above 11V.

**Comment by tomek-szczesny** [comment]
I propose to change `editVolt` because that's the function triggered by the knob.
Clamping variable to range should not be affected because the valid range (min/max voltage) is still the same, I think.  

`volt_set` should be fixed too, because this function will most likely be used for remote control, if it ever gets implemented, as you pointed out.

The array of permissible values, also known as LUT or Look Up Table, is also something I've been thinking about. There are about 250 possible voltages, so the array would be ~512B (assuming 16-bit integers). I can't remember how big RAM is, but I think it was about 1MB or 2MB - we could safely invest 512B for LUT.

Or try this algorithm I just came up with:
```
// Limit volt_set to (-44 : +44)
old = this->volt_set;
if (old > 5900 && old < 11000) {
    new = old + volt_set*100;   // Proceed like before
    if (new > 11000) new += (new - 11000);  // Double the steps over 11000 by adding that portion again to the result
    if (new < 5900) new += (5900 - new) * (4/5); // shrink steps below 5900 by adding back 4/5 of what was taken
}
if (old <= 5900) {
    new = old + volt_set*20; 
    if (new > 5900) new += (new - 5900) * 4; // expand 20mV steps above 5900 into 100mV steps
}
if (old >= 11000) {
    new = old + volt_set*200;
    if (new < 11000) new += (11000 - new) / 2; // Shrink negative 200mV steps into 100mV steps
}
if (new > 20000) new = 20000;
if (new < 3000) new = 3000;
this->_volt_set = new;
```

**Comment by cedel1** [comment]
Thanks for the algorithm, I'll look into it.

> Clamping variable to range should not be affected because the valid range (min/max voltage) is still the same, I think.

I don't think so - if you look at `Screen::changeVolt` method, you'll see that:
1. the `volt_set` used in `editVolt` and `setVolt` methods is really the number of encoder steps.
2. the "clamping" in the `changeVolt` method "clamps" the number of encoder steps
3. and since the `editVolt` and `setVolt` methods take difference to "old" value in the number of steps, it is necessary to change the "clamping" of steps, because the number of permissible steps in each direction changes with the "old" value.

**Comment by tomek-szczesny** [comment]
Well, if you ask me, that looks like a total mess. Can we get rid of that encoder steps clamping method? Unless there is a good reason behind it.

Instead we could just add this to `editVolt` and `setVolt`, an actual voltage setting clamp.
```
if (new > 20000) new = 20000;
if (new < 3000) new = 3000;
// Apply "new" as a new output voltage value
```

EDIT: I added this to my proposed algorithm above.

**Comment by cedel1** [comment]
> Well, if you ask me, that looks like a total mess.

It's a bit complicated, but I think it has a reason - suppose one turns the encoder past the limit (upper or lower, does not matter) and the encoder keeps counting. Then, before pressing the settings button, you change your mind and want to go in the other direction. If the clamping wasn't there and the encoder kept adding/subtracting, you would have to go the same distance backwards before getting past the limit. 
Suppose the upper limit is 20 steps, you keep turning encoder and counting to, let's say, 40. No if you want to go to 15, you would still have to turn 25 steps backwards instead of just 5. The extra steps past the limit would not be discarded.

**Comment by tomek-szczesny** [comment]
Well, that only shows you understand this code way better than I do!

Fair enough! Here's a formula for calculating on which step we currently are, assuming 3V is step number 0. This can serve to obtain step clamping limits accordingly.

```
if (old > 5900) {
  step = (5900 - 3000) / 20;
  if (old > 11000) {
    step += (11000 - 5900) / 100;
    step += (old - 11000) / 200;
  }
  else step += (old - 5900) / 100;
}
else step = (old - 3000) / 20;
```
