### ISSUE TITLE
Fan settings need to go

### ISSUE THREAD

**Issue by tomek-szczesny** [hardkernel/smartpower3#5]
There is no fan in my unit and I don't think it's special in any way. :)

The presence of nonfunctional setting leads to nothing more but confusing the users.

**Comment by leeseungcheol** [comment]
We are going to remove the fan feature in the next release.

Thank you. :)

**Comment by tomek-szczesny** [comment]
It is fixed, but one warning appears while building. Some variable was left behind. :)

**Comment by leeseungcheol** [comment]
I close the issue.
I removed the unused variable.
350858dd000060e7ba641c90c8a910dda124cca9

Thank you.
