### ISSUE TITLE
Changing baudrate or interval sometimes resets the unit

### ISSUE THREAD

**Issue by tomek-szczesny** [hardkernel/smartpower3#6]
I haven't found exact steps to reliably reproduce the problem, but at about 10% of cases, the unit resets after selecting desired baudrate or interval (at the knob push).

**Comment by tomek-szczesny** [comment]
Yesterday I triggered this bug again, and I saw it wrote something in Serial console, some debug information.
I was busy testing something else so I didn't investigate it yet.

**Comment by leeseungcheol** [comment]
I have duplicated the issue. This is the known issue in ESP32.
[https://www.esp32.com/viewtopic.php?t=7684](url)

First of all, I committed a workaround for the unexpected reset.
2bf63e1d00b9c51086429ae1d8c1ed60d1dc1a10

**Comment by tomek-szczesny** [comment]
Excellent, thank you! I can't test it this week, but if it is possible to change baud rate 20 times or so, I think it may be closed for now, and reopened if someone finds that the problem persists.

**Comment by tomek-szczesny** [comment]
It seems to work fine now. Thanks for the fix, closing!
